### ISSUE TITLE
No database setting up steps in README

### ISSUE THREAD

**Issue by damianochintala** [collins-droid/laravel-weather-app#1]
### Description:
When running the application, the following error occurs because the SQLite database file is missing or the path to the database file is incorrect:

Database file at path /file/path does not exist. Ensure this is an absolute path to the database. 

### Steps to Reproduce:
1. Cloned the repository.
2. Set up the project by following the instructions in the README.
3. Ran the application.
4. Encountered the error when the application tries to connect to the SQLite database.

### Expected Behavior:
The application should connect to the database without errors, or the README file should include instructions on how to create the database file and provide the correct path.

### Suggested Fix:
- Ensure that the database file is either created automatically if it does not exist, or provide clear instructions on how to create and configure it.
- Verify that the database path is correctly set in the application's configuration.
- If the project requires manual database setup, update the README with detailed setup instructions.

**Comment by collins-droid** [comment]
thanks damianochintala it totally slipped my mind ! ,I will update the Readme and commit shortly
